#!/bin/bash

mkdir -p pkg/api/v1

protoc \
    --proto_path=api/v1 \
    --go_out=pkg/api/v1 \
    --go_opt=paths=source_relative \
    --go-grpc_out=pkg/api/v1 \
    --go-grpc_opt=paths=source_relative \
    sample.proto
