name: on_tag
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'  # Only build tag with semantic versioning format

permissions:
  contents: read

jobs:

  conf:
    env:
      # Update as needed
      IMG_NAME: s3cme
      GO_VERSION: '1.21.6'
      COSIGN_VERSION: v2.2.2
      ERR_VULNERABILITY_SEV: 'CRITICAL,HIGH,MEDIUM'

    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      image_name: ${{ steps.conf.outputs.image_name }}
      go_version: ${{ steps.conf.outputs.go_version }}
      cosign_version: ${{ steps.conf.outputs.cosign_version }}
      err_on_vulnerability_sev: ${{ steps.conf.outputs.err_on_vulnerability_sev }}
    steps:
    - name: Export Config
      id: conf
      run: |
        echo "image_name=${{ env.IMG_NAME }}" >> $GITHUB_OUTPUT
        echo "go_version=${{ env.GO_VERSION }}" >> $GITHUB_OUTPUT
        echo "cosign_version=${{ env.COSIGN_VERSION }}" >> $GITHUB_OUTPUT
        echo "err_on_vulnerability_sev=${{ env.ERR_VULNERABILITY_SEV }}" >> $GITHUB_OUTPUT

  test:
    needs:
    - conf
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: ./.github/workflows/test.yaml
    with:
      go_version: ${{ needs.conf.outputs.go_version }}
      scan_severity: ${{ needs.conf.outputs.err_on_vulnerability_sev }}

  build:
    needs:
    - conf
    - test
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yaml
    with:
      go_version: ${{ needs.conf.outputs.go_version }}
      image_name: ${{ needs.conf.outputs.image_name }}

  sign:
    needs:
    - conf
    - build
    permissions:
      contents: read
      actions: read
      packages: write
    uses: ./.github/workflows/sign.yaml
    with:
      cosign_version: ${{ needs.conf.outputs.cosign_version }}
      image_digest: ${{ needs.build.outputs.digest }}

  scan:
    needs:
    - conf
    - build
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/scan.yaml
    with:
      image_digest: ${{ needs.build.outputs.digest }}
      scan_severity: ${{ needs.conf.outputs.err_on_vulnerability_sev }}

  slsa:
    needs:
    - conf
    - build
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    uses: ./.github/workflows/slsa.yaml
    with:
      image_digest: ${{ needs.build.outputs.digest }}
